import Header from './components/Header';
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ["latin"], weight:['400','500','600','700','800','900'] });

export const metadata = {
  title: 'next js crud operation',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className='max-w-4xl mx-auto px-5'>
        <Header/>
        {children}</div>
      </body>
    </html>
  );
}
